spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pingwin
    username: postgres
    password: prozniecki600
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    user:
      name: admin
      password: secret
