spring:
  datasource:
    url: "jdbc:${dbRDBMS}://${dbHost}:${dbPort}/${dbDatabase}"
    username: $dbUsername
    password: $dbPassword
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  security:
    user:
      name: admin
      password: secret
